import React, { useState } from 'react';
import { 
  Braces, 
  UploadCloud, 
  Download, 
  Sparkles, 
  FileText, 
  CheckCircle2, 
  Layers 
} from 'lucide-react';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import confetti from 'canvas-confetti';
import { sfx } from '@/core/audio/sfx';

const DEFAULT_JSON = `{
  "reportTitle": "Quarterly Financial Analytics",
  "version": "2.4.0",
  "generatedAt": "${new Date().toISOString()}",
  "metrics": {
    "totalRevenue": "$1,450,000",
    "grossMargin": "74.2%",
    "activeSubscribers": 14200,
    "complianceScore": 99.8
  },
  "auditLog": [
    { "id": "AUD-01", "event": "AES-256 Vault Rotation", "status": "PASSED" },
    { "id": "AUD-02", "event": "Client Zero-Knowledge Verification", "status": "VERIFIED" },
    { "id": "AUD-03", "event": "WASM Memory Sandbox Check", "status": "NOMINAL" }
  ]
}`;

export const JsonToPdfTool: React.FC<{ onClose: () => void }> = ({ onClose }) => {
  const [jsonText, setJsonText] = useState<string>(DEFAULT_JSON);
  const [isProcessing, setIsProcessing] = useState<boolean>(false);
  const [parsedData, setParsedData] = useState<any>(null);
  const [isValid, setIsValid] = useState<boolean>(true);

  const handleJsonChange = (val: string) => {
    setJsonText(val);
    try {
      const parsed = JSON.parse(val);
      setParsedData(parsed);
      setIsValid(true);
    } catch {
      setIsValid(false);
    }
  };

  const handleExportPdf = async () => {
    try {
      const data = JSON.parse(jsonText);
      setIsProcessing(true);
      sfx.playScan();

      const pdfDoc = await PDFDocument.create();
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
      const fontMono = await pdfDoc.embedFont(StandardFonts.Courier);

      const page = pdfDoc.addPage([595, 842]); // A4
      const { width, height } = page.getSize();
      const margin = 40;
      let currentY = height - margin;

      // Header Banner
      page.drawRectangle({
        x: margin,
        y: currentY - 25,
        width: width - (margin * 2),
        height: 25,
        color: rgb(0.08, 0.12, 0.22),
      });

      page.drawText('STRUCTURED JSON EXECUTIVE DATA REPORT', {
        x: margin + 12,
        y: currentY - 17,
        size: 10,
        font: fontBold,
        color: rgb(0.2, 0.8, 1.0),
      });
      currentY -= 45;

      // Recursive render JSON key/values
      const renderObject = (obj: any, indent: number) => {
        for (const [key, value] of Object.entries(obj)) {
          if (currentY < margin + 30) break;

          if (typeof value === 'object' && value !== null) {
            page.drawText(`${' '.repeat(indent * 2)}▸ ${key}:`, {
              x: margin + (indent * 12),
              y: currentY,
              size: 10,
              font: fontBold,
              color: rgb(0.3, 0.4, 0.8),
            });
            currentY -= 16;
            renderObject(value, indent + 1);
          } else {
            // Draw Key
            page.drawText(`${key}:`, {
              x: margin + (indent * 12),
              y: currentY,
              size: 9,
              font: fontBold,
              color: rgb(0.15, 0.15, 0.2),
            });

            // Draw Value
            const valStr = String(value);
            page.drawText(valStr, {
              x: margin + (indent * 12) + 120,
              y: currentY,
              size: 9,
              font: fontMono,
              color: rgb(0.1, 0.5, 0.4),
            });

            currentY -= 15;
          }
        }
      };

      renderObject(data, 0);

      // Footer
      page.drawText(`Generated by AETHER Data Engine • ${new Date().toLocaleDateString()}`, {
        x: margin,
        y: 20,
        size: 8,
        font,
        color: rgb(0.6, 0.6, 0.6),
      });

      const pdfBytes = await pdfDoc.save();
      const blob = new Blob([pdfBytes as any], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `json-report-${Date.now()}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      sfx.playSuccess();
      confetti({ particleCount: 50, spread: 60, origin: { y: 0.6 } });
    } catch (err) {
      console.error('JSON to PDF error:', err);
      alert('Invalid JSON structure.');
      sfx.playError();
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between text-xs font-fira">
        <span className="text-slate-400 font-bold">Input JSON / Data Payload</span>
        <span className={isValid ? 'text-emerald-400 font-bold' : 'text-rose-400 font-bold'}>
          {isValid ? 'Valid JSON' : 'Syntax Error in JSON'}
        </span>
      </div>

      <textarea
        value={jsonText}
        onChange={(e) => handleJsonChange(e.target.value)}
        rows={14}
        className="w-full rounded-2xl bg-black/60 border border-white/10 p-3.5 text-xs font-mono text-cyan-300 focus:border-cyan-400 focus:outline-none resize-none leading-relaxed"
      />

      <div className="flex justify-end pt-2">
        <button
          onClick={handleExportPdf}
          disabled={!isValid || isProcessing}
          className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-purple-500 to-indigo-500 hover:from-purple-400 hover:to-indigo-400 text-white font-bold font-fira text-xs shadow-lg shadow-purple-500/20 flex items-center gap-2 cursor-pointer disabled:opacity-50"
        >
          <Braces className="w-4 h-4" />
          Compile Structured PDF Report
        </button>
      </div>
    </div>
  );
};