import { ToolDefinition, CategoryDefinition, ToolCategory } from '../types/tool';

export const CATEGORIES: CategoryDefinition[] = [
  {
    id: 'essentials',
    name: 'Essentials & Imposition',
    tagline: 'Merge, split, compress, crop, and reorder pages with zero quality loss.',
    iconName: 'Layers',
    accentColor: 'cyan',
  },
  {
    id: 'edit',
    name: 'Vector Studio & Editor',
    tagline: 'In-place text editing, bézier signature studio, redaction, and stamps.',
    iconName: 'PenTool',
    accentColor: 'blue',
  },
  {
    id: 'security',
    name: 'Security & Forensics',
    tagline: 'AES-256 encryption, PII auto-redact, metadata stripper, and repair.',
    iconName: 'ShieldCheck',
    accentColor: 'emerald',
  },
  {
    id: 'convert-to-pdf',
    name: 'Convert to PDF',
    tagline: 'Transform Office, Images, Markdown, HTML, Audio, and E-books into PDF.',
    iconName: 'FileInput',
    accentColor: 'purple',
  },
  {
    id: 'convert-from-pdf',
    name: 'Convert from PDF',
    tagline: 'Export to Word (.docx), Excel (.xlsx), 600 DPI Images, HTML, and TTS Audio.',
    iconName: 'FileOutput',
    accentColor: 'amber',
  },
  {
    id: 'ai-intelligence',
    name: 'AI Intelligence Studio',
    tagline: 'RAG Chat with citations, executive summarizer, translation, and WASM OCR.',
    iconName: 'BrainCircuit',
    accentColor: 'purple',
  },
  {
    id: 'super-modules',
    name: 'Cyber Super-Modules',
    tagline: 'Visual node automation, 3D holographic flipbook, and P2P WebRTC sharing.',
    iconName: 'Sparkles',
    accentColor: 'cyan',
  },
  {
    id: 'business',
    name: 'Commerce & Invoicing',
    tagline: 'GST invoice generator, POS thermal receipts, and tax filing tools.',
    iconName: 'Receipt',
    accentColor: 'amber',
  },
];

export const TOOLS_REGISTRY: ToolDefinition[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. ESSENTIALS & IMPOSITION
  // ─────────────────────────────────────────────────────────────
  {
    id: 'merge-pdf',
    title: 'Merge PDFs',
    description: 'Combine multiple PDF files into one master document with drag-and-drop ordering.',
    category: 'essentials',
    iconName: 'CopyPlus',
    badge: 'HOT',
    accentColor: 'cyan',
    keywords: ['merge', 'combine', 'join', 'concat', 'bind'],
    shortcut: 'M',
    isFeatured: true,
  },
  {
    id: 'alternate-mix-pdf',
    title: 'Alternate & Mix PDF',
    description: 'Interleave two scanned documents (odd and even pages) in alternating sequence.',
    category: 'essentials',
    iconName: 'Shuffle',
    accentColor: 'cyan',
    keywords: ['alternate', 'mix', 'interleave', 'duplex', 'scan'],
  },
  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Multi-level size reduction with lossless vector compression and image subsampling.',
    category: 'essentials',
    iconName: 'Minimize2',
    badge: 'FAST',
    accentColor: 'emerald',
    keywords: ['compress', 'shrink', 'reduce', 'optimize', 'size'],
    shortcut: 'C',
    isFeatured: true,
  },
  {
    id: 'split-pdf',
    title: 'Split by Range',
    description: 'Extract specific pages or custom range intervals (e.g., 1-4, 7, 9-12).',
    category: 'essentials',
    iconName: 'Scissors',
    accentColor: 'cyan',
    keywords: ['split', 'extract', 'range', 'cut', 'separate'],
    shortcut: 'S',
    isFeatured: true,
  },
  {
    id: 'split-by-text',
    title: 'Split by Text Match',
    description: 'Automatically divide document into separate files whenever specific keywords occur.',
    category: 'essentials',
    iconName: 'SearchCode',
    badge: 'NEW',
    accentColor: 'cyan',
    keywords: ['split', 'keyword', 'regex', 'text', 'match'],
  },
  {
    id: 'split-by-bookmarks',
    title: 'Split by Bookmarks',
    description: 'Split document into chapters based on embedded PDF bookmark hierarchy.',
    category: 'essentials',
    iconName: 'Bookmark',
    accentColor: 'cyan',
    keywords: ['split', 'bookmark', 'outline', 'chapters', 'toc'],
  },
  {
    id: 'split-in-half',
    title: 'Split PDF in Half',
    description: 'Cut scanned two-page spreads horizontally or vertically into individual pages.',
    category: 'essentials',
    iconName: 'Columns2',
    accentColor: 'cyan',
    keywords: ['split', 'half', 'booklet', 'columns', 'spreads'],
  },
  {
    id: 'split-by-size',
    title: 'Split by File Size',
    description: 'Partition large documents into targeted megabyte limits (e.g. <5MB for email).',
    category: 'essentials',
    iconName: 'PieChart',
    accentColor: 'cyan',
    keywords: ['split', 'size', 'megabytes', 'chunk', 'email'],
  },
  {
    id: 'organize-pages',
    title: 'Organize & Reorder Pages',
    description: 'Interactive visual grid to rearrange, duplicate, invert, or delete individual pages.',
    category: 'essentials',
    iconName: 'LayoutGrid',
    badge: 'HOT',
    accentColor: 'blue',
    keywords: ['organize', 'reorder', 'rearrange', 'sort', 'delete', 'thumbnails'],
    shortcut: 'O',
    isFeatured: true,
  },
  {
    id: 'rotate-pdf',
    title: 'Rotate & Auto-Deskew',
    description: 'Rotate 90°/180°/270° and automatically detect and fix skewed, crooked scans.',
    category: 'essentials',
    iconName: 'RotateCw',
    accentColor: 'cyan',
    keywords: ['rotate', 'deskew', 'orientation', 'upside down', 'sideways'],
  },
  {
    id: 'flip-pdf',
    title: 'Flip PDF (Mirror)',
    description: 'Mirror PDF pages horizontally or vertically for printing and transfers.',
    category: 'essentials',
    iconName: 'FlipHorizontal',
    accentColor: 'cyan',
    keywords: ['flip', 'mirror', 'invert', 'horizontal', 'vertical'],
  },
  {
    id: 'n-up-pdf',
    title: 'Multiple Pages Per Sheet (N-Up)',
    description: 'Impose 2, 4, 6, 8 or 9 pages onto a single sheet with custom borders.',
    category: 'essentials',
    iconName: 'Grid',
    accentColor: 'blue',
    keywords: ['n-up', 'grid', 'booklet', 'multiple', 'sheet', 'handout'],
  },
  {
    id: 'crop-resize-pdf',
    title: 'Crop & Resize Pages',
    description: 'Trim margins and standardize dimensions to A4, A3, US Letter, or Legal.',
    category: 'essentials',
    iconName: 'Crop',
    accentColor: 'cyan',
    keywords: ['crop', 'resize', 'margin', 'trim', 'a4', 'letter'],
  },

  // ─────────────────────────────────────────────────────────────
  // 2. VECTOR STUDIO & VISUAL EDITOR
  // ─────────────────────────────────────────────────────────────
  {
    id: 'edit-pdf-text',
    title: 'In-Place Text Editor',
    description: 'Click any existing text on the PDF to modify, retype, and recolor with matching font.',
    category: 'edit',
    iconName: 'Type',
    badge: 'PRO',
    accentColor: 'blue',
    keywords: ['edit', 'text', 'modify', 'typo', 'font', 'write'],
    shortcut: 'E',
    isFeatured: true,
  },
  {
    id: 'sign-pdf',
    title: 'Digital Signature Studio',
    description: 'Smooth Bézier pen signature, calligraphy fonts, image stamp, and verification badges.',
    category: 'edit',
    iconName: 'FileSignature',
    badge: 'HOT',
    accentColor: 'emerald',
    keywords: ['sign', 'signature', 'draw', 'calligraphy', 'stamp', 'signet'],
    shortcut: 'G',
    isFeatured: true,
  },
  {
    id: 'fill-pdf-form',
    title: 'Interactive Form Filler',
    description: 'Fill out standard AcroForms text fields, checkboxes, radio buttons, and dropdowns.',
    category: 'edit',
    iconName: 'CheckSquare',
    accentColor: 'blue',
    keywords: ['fill', 'form', 'acroforms', 'checkbox', 'text field'],
  },
  {
    id: 'create-form-fields',
    title: 'Fillable Form Creator',
    description: 'Add new interactive text fields, checkboxes, and signature blocks onto flat PDFs.',
    category: 'edit',
    iconName: 'FormInput',
    badge: 'NEW',
    accentColor: 'blue',
    keywords: ['create form', 'add inputs', 'interactive', 'fields'],
  },
  {
    id: 'redact-pdf',
    title: 'Permanent Vector Redaction',
    description: 'Destroy underlying text streams and permanently black out confidential data.',
    category: 'edit',
    iconName: 'EyeOff',
    badge: 'PRO',
    accentColor: 'rose',
    keywords: ['redact', 'blackout', 'hide', 'confidential', 'censor'],
    shortcut: 'R',
    isFeatured: true,
  },
  {
    id: 'add-watermark',
    title: 'Add Watermark Studio',
    description: 'Overlay custom text, company logo images, diagonal stamps, or tiled patterns.',
    category: 'edit',
    iconName: 'Stamp',
    accentColor: 'cyan',
    keywords: ['watermark', 'stamp', 'confidential', 'logo', 'copyright'],
  },
  {
    id: 'add-page-numbers',
    title: 'Page Numbering Studio',
    description: 'Insert dynamic page numbers with Roman numerals, prefix/suffix, and offsets.',
    category: 'edit',
    iconName: 'ListOrdered',
    accentColor: 'blue',
    keywords: ['page numbers', 'paginate', 'footer', 'numbering', 'roman'],
  },
  {
    id: 'bates-numbering',
    title: 'Bates Numbering (Legal)',
    description: 'Legal sequential label formatting with zero-padding (e.g. LAW-000420).',
    category: 'edit',
    iconName: 'Binary',
    accentColor: 'blue',
    keywords: ['bates', 'legal', 'law', 'discovery', 'sequential'],
  },
  {
    id: 'headers-footers',
    title: 'Headers & Footers',
    description: 'Custom multi-column headers and footers with date, title, and page variables.',
    category: 'edit',
    iconName: 'Heading',
    accentColor: 'blue',
    keywords: ['header', 'footer', 'top', 'bottom', 'title'],
  },
  {
    id: 'vector-annotate',
    title: 'Figma-Grade Annotations',
    description: 'Highlighters, callout arrows, freehand stylus, rectangles, and sticky notes.',
    category: 'edit',
    iconName: 'Highlighter',
    accentColor: 'amber',
    keywords: ['annotate', 'markup', 'highlight', 'draw', 'shapes', 'arrows'],
  },
  {
    id: 'whiteout-pdf',
    title: 'Whiteout & Eraser',
    description: 'Cleanly erase unwanted text, graphics, or borders with precise vector patches.',
    category: 'edit',
    iconName: 'Eraser',
    accentColor: 'blue',
    keywords: ['whiteout', 'erase', 'remove', 'clean', 'mask'],
  },
  {
    id: 'flatten-pdf',
    title: 'Flatten Document',
    description: 'Bake all form inputs, annotations, and signatures into non-editable vector paths.',
    category: 'edit',
    iconName: 'Layers2',
    accentColor: 'emerald',
    keywords: ['flatten', 'lock', 'secure', 'bake', 'non-editable'],
  },
  {
    id: 'invert-pdf-colors',
    title: 'Dark Mode / Sepia Inverter',
    description: 'Transform documents into OLED Midnight Dark Mode, Sepia, or High Contrast.',
    category: 'edit',
    iconName: 'Moon',
    badge: 'HOT',
    accentColor: 'purple',
    keywords: ['dark mode', 'invert', 'sepia', 'night', 'colors', 'oled'],
  },
  {
    id: 'handwriting-simulator',
    title: 'Handwriting Humanizer',
    description: 'Convert typed digital text into realistic, organic simulated human handwriting.',
    category: 'edit',
    iconName: 'Feather',
    badge: 'NEW',
    accentColor: 'amber',
    keywords: ['handwriting', 'humanizer', 'pen', 'notes', 'script'],
  },

  // ─────────────────────────────────────────────────────────────
  // 3. SECURITY, CRYPTOGRAPHY & FORENSICS
  // ─────────────────────────────────────────────────────────────
  {
    id: 'encrypt-pdf',
    title: 'AES-256 Encrypt & Locker',
    description: 'Lock PDF with military-grade AES-256 and restrict printing, copying, or modifying.',
    category: 'security',
    iconName: 'Lock',
    badge: 'PRO',
    accentColor: 'emerald',
    keywords: ['encrypt', 'password', 'protect', 'lock', 'aes-256'],
    shortcut: 'L',
    isFeatured: true,
  },
  {
    id: 'unlock-pdf',
    title: 'Unlock & Decrypt PDF',
    description: 'Remove password restrictions and decrypt protected files locally in-browser.',
    category: 'security',
    iconName: 'Unlock',
    accentColor: 'emerald',
    keywords: ['unlock', 'decrypt', 'remove password', 'unprotect'],
  },
  {
    id: 'auto-redact-pii',
    title: 'Auto-Redact Sensitive PII',
    description: 'Automatic detection and instant masking of Aadhaar, PAN, SSN, Credit Cards & Emails.',
    category: 'security',
    iconName: 'ShieldAlert',
    badge: 'AI',
    accentColor: 'rose',
    keywords: ['pii', 'privacy', 'aadhaar', 'pan', 'ssn', 'credit card', 'auto-redact'],
    isFeatured: true,
  },
  {
    id: 'privacy-scanner',
    title: 'Privacy Risk Scanner',
    description: 'Scan and purge embedded GPS exif data, author identity, software trails, and metadata.',
    category: 'security',
    iconName: 'Radar',
    badge: 'PRO',
    accentColor: 'emerald',
    keywords: ['metadata', 'privacy', 'exif', 'gps', 'author', 'sanitize'],
  },
  {
    id: 'fingerprint-pdf',
    title: 'Steganographic Leak Tracker',
    description: 'Inject microscopic, invisible tracking fingerprints to detect the source of document leaks.',
    category: 'security',
    iconName: 'Fingerprint',
    badge: 'NEW',
    accentColor: 'purple',
    keywords: ['fingerprint', 'canary', 'steganography', 'leak', 'track'],
  },
  {
    id: 'repair-pdf',
    title: '5-Strategy Forensic Repair',
    description: 'Rebuild broken cross-reference (xref) tables, missing headers, and truncated streams.',
    category: 'security',
    iconName: 'Wrench',
    badge: 'WASM',
    accentColor: 'amber',
    keywords: ['repair', 'fix', 'corrupt', 'broken', 'recover', 'xref'],
  },
  {
    id: 'pdf-sanitizer',
    title: 'Malware & Script Sanitizer',
    description: 'Strip malicious embedded JavaScript, Launch triggers, and external tracking beacons.',
    category: 'security',
    iconName: 'ShieldMinus',
    accentColor: 'emerald',
    keywords: ['sanitize', 'malware', 'javascript', 'beacons', 'clean'],
  },
  {
    id: 'pdf-a-converter',
    title: 'PDF/A Legal Archival',
    description: 'Convert PDFs into ISO-compliant PDF/A-1b / PDF/A-2b format for permanent storage.',
    category: 'security',
    iconName: 'Archive',
    accentColor: 'emerald',
    keywords: ['pdf/a', 'archive', 'iso', 'legal', 'compliance'],
  },
  {
    id: 'forensic-inspector',
    title: 'Low-Level Hex & Object Tree',
    description: 'Interactive low-level inspection of PDF dictionary nodes, xref tables, and raw hex bytes.',
    category: 'security',
    iconName: 'Cpu',
    badge: 'PRO',
    accentColor: 'cyan',
    keywords: ['hex', 'forensics', 'objects', 'xref', 'byte', 'inspector'],
  },

  // ─────────────────────────────────────────────────────────────
  // 4. CONVERT TO PDF
  // ─────────────────────────────────────────────────────────────
  {
    id: 'word-to-pdf',
    title: 'Word (.docx) to PDF',
    description: 'Convert Word documents to crisp PDFs with exact typography and table fidelity.',
    category: 'convert-to-pdf',
    iconName: 'FileText',
    badge: 'WASM',
    accentColor: 'purple',
    keywords: ['word', 'docx', 'doc', 'convert', 'office'],
    isFeatured: true,
  },
  {
    id: 'excel-to-pdf',
    title: 'Excel (.xlsx) to PDF',
    description: 'Transform spreadsheets into structured, beautiful multi-page PDF tables.',
    category: 'convert-to-pdf',
    iconName: 'Sheet',
    accentColor: 'purple',
    keywords: ['excel', 'xlsx', 'xls', 'spreadsheet', 'sheets'],
  },
  {
    id: 'pptx-to-pdf',
    title: 'PowerPoint (.pptx) to PDF',
    description: 'Convert slide presentations into vector PDF slide decks.',
    category: 'convert-to-pdf',
    iconName: 'Presentation',
    accentColor: 'purple',
    keywords: ['powerpoint', 'pptx', 'ppt', 'slides', 'presentation'],
  },
  {
    id: 'images-to-pdf',
    title: 'Images to PDF',
    description: 'Batch convert JPG, PNG, WEBP, GIF, SVG, BMP and HEIC photos into a unified PDF.',
    category: 'convert-to-pdf',
    iconName: 'Images',
    badge: 'FAST',
    accentColor: 'purple',
    keywords: ['images', 'jpg', 'png', 'webp', 'heic', 'photos'],
    isFeatured: true,
  },
  {
    id: 'markdown-to-pdf',
    title: 'Markdown (.md) to PDF',
    description: 'Render Markdown with KaTeX math formulas, Mermaid diagrams, and code syntax highlighting.',
    category: 'convert-to-pdf',
    iconName: 'FileCode',
    accentColor: 'purple',
    keywords: ['markdown', 'md', 'katex', 'mermaid', 'syntax'],
  },
  {
    id: 'html-to-pdf',
    title: 'HTML / Webpage to PDF',
    description: 'Convert raw HTML code or web content into a styled, printable PDF document.',
    category: 'convert-to-pdf',
    iconName: 'Globe',
    accentColor: 'purple',
    keywords: ['html', 'webpage', 'url', 'css', 'website'],
  },
  {
    id: 'csv-to-pdf',
    title: 'CSV / TSV to PDF Table',
    description: 'Convert raw CSV data into formatted, beautifully styled PDF ledger tables.',
    category: 'convert-to-pdf',
    iconName: 'Table',
    accentColor: 'purple',
    keywords: ['csv', 'tsv', 'data', 'table', 'dataset'],
  },
  {
    id: 'json-to-pdf',
    title: 'JSON / YAML to PDF Report',
    description: 'Convert JSON data trees into structured executive reports with colorized schemas.',
    category: 'convert-to-pdf',
    iconName: 'Braces',
    accentColor: 'purple',
    keywords: ['json', 'yaml', 'data', 'api', 'schema'],
  },
  {
    id: 'audio-to-pdf',
    title: 'Audio (Whisper) to PDF',
    description: 'Transcribe MP3/WAV audio recordings into a formatted PDF meeting transcript.',
    category: 'convert-to-pdf',
    iconName: 'Mic',
    badge: 'AI',
    accentColor: 'purple',
    keywords: ['audio', 'whisper', 'transcribe', 'voice', 'speech', 'meeting'],
  },
  {
    id: 'ebook-to-pdf',
    title: 'eBook (EPUB/MOBI) to PDF',
    description: 'Convert EPUB, MOBI, and AZW3 digital books into readable PDF documents.',
    category: 'convert-to-pdf',
    iconName: 'BookOpen',
    accentColor: 'purple',
    keywords: ['ebook', 'epub', 'mobi', 'kindle', 'book'],
  },
  {
    id: 'create-pdf',
    title: 'WYSIWYG PDF Studio',
    description: 'Blank canvas rich-text document creator with live layout preview and export.',
    category: 'convert-to-pdf',
    iconName: 'FilePlus',
    accentColor: 'purple',
    keywords: ['create', 'blank', 'wysiwyg', 'write', 'author'],
  },

  // ─────────────────────────────────────────────────────────────
  // 5. CONVERT FROM PDF
  // ─────────────────────────────────────────────────────────────
  {
    id: 'pdf-to-word',
    title: 'PDF to Word (.docx)',
    description: 'Convert PDF pages into editable Microsoft Word (.docx) files with layout preservation.',
    category: 'convert-from-pdf',
    iconName: 'FileText',
    badge: 'PRO',
    accentColor: 'amber',
    keywords: ['pdf to word', 'docx', 'doc', 'editable', 'extract'],
    isFeatured: true,
  },
  {
    id: 'pdf-to-excel',
    title: 'PDF to Excel (.xlsx)',
    description: 'Auto-detect table grids inside PDFs and extract clean numerical Excel spreadsheets.',
    category: 'convert-from-pdf',
    iconName: 'Sheet',
    accentColor: 'amber',
    keywords: ['pdf to excel', 'xlsx', 'spreadsheet', 'table', 'financials'],
  },
  {
    id: 'pdf-to-pptx',
    title: 'PDF to PowerPoint (.pptx)',
    description: 'Convert PDF pages into editable PowerPoint slide decks.',
    category: 'convert-from-pdf',
    iconName: 'Presentation',
    accentColor: 'amber',
    keywords: ['pdf to pptx', 'powerpoint', 'slides', 'deck'],
  },
  {
    id: 'pdf-to-jpg',
    title: 'PDF to High-Res JPG/PNG',
    description: 'Export pages as images from 150 DPI web resolution up to 600 DPI archival quality.',
    category: 'convert-from-pdf',
    iconName: 'Image',
    badge: 'FAST',
    accentColor: 'amber',
    keywords: ['pdf to jpg', 'png', '600 dpi', 'high res', 'export images'],
    isFeatured: true,
  },
  {
    id: 'pdf-to-svg',
    title: 'PDF to Vector SVG',
    description: 'Extract pure scalable vector graphics (SVG) without pixelation.',
    category: 'convert-from-pdf',
    iconName: 'VectorSquare',
    accentColor: 'amber',
    keywords: ['svg', 'vector', 'scalable', 'illustrator', 'graphics'],
  },
  {
    id: 'pdf-to-html',
    title: 'PDF to Webpage HTML',
    description: 'Convert PDF to responsive, searchable HTML with selectable text layers.',
    category: 'convert-from-pdf',
    iconName: 'Code',
    accentColor: 'amber',
    keywords: ['pdf to html', 'web', 'responsive', 'searchable'],
  },
  {
    id: 'pdf-to-markdown',
    title: 'PDF to Markdown (.md)',
    description: 'Extract text, tables, and headers formatted cleanly as standard Markdown.',
    category: 'convert-from-pdf',
    iconName: 'FileCode2',
    accentColor: 'amber',
    keywords: ['pdf to md', 'markdown', 'extract text', 'clean'],
  },
  {
    id: 'pdf-to-epub',
    title: 'PDF to EPUB eBook',
    description: 'Reflow PDF document text for comfortable reading on Apple Books and Kindle.',
    category: 'convert-from-pdf',
    iconName: 'Book',
    accentColor: 'amber',
    keywords: ['epub', 'kindle', 'ereader', 'reflow'],
  },
  {
    id: 'pdf-to-audio',
    title: 'PDF to Audio (TTS Reader)',
    description: 'Convert document text into natural-sounding speech with neural voice synthesizer.',
    category: 'convert-from-pdf',
    iconName: 'Volume2',
    badge: 'AI',
    accentColor: 'purple',
    keywords: ['tts', 'text to speech', 'audiobook', 'listen', 'voice'],
  },
  {
    id: 'pdf-to-zip',
    title: 'PDF to ZIP Archive',
    description: 'Package all rendered pages as individual high-res images in a single ZIP download.',
    category: 'convert-from-pdf',
    iconName: 'Archive',
    accentColor: 'amber',
    keywords: ['zip', 'archive', 'package', 'bulk export'],
  },

  // ─────────────────────────────────────────────────────────────
  // 6. AI INTELLIGENCE STUDIO
  // ─────────────────────────────────────────────────────────────
  {
    id: 'chat-with-pdf',
    title: 'Chat with PDF (RAG + Citations)',
    description: 'Ask deep questions and get instant answers with clickable page coordinate citations.',
    category: 'ai-intelligence',
    iconName: 'MessageSquareText',
    badge: 'AI',
    accentColor: 'purple',
    keywords: ['ai', 'chat', 'gemini', 'rag', 'questions', 'citations'],
    shortcut: 'Q',
    isFeatured: true,
  },
  {
    id: 'summarize-pdf',
    title: 'Multi-Format AI Summarizer',
    description: 'Generate Executive Briefs, Key Takeaway Bullets, or Action Item checklists instantly.',
    category: 'ai-intelligence',
    iconName: 'Sparkles',
    badge: 'AI',
    accentColor: 'purple',
    keywords: ['summarize', 'tldr', 'executive summary', 'bullets', 'ai'],
    isFeatured: true,
  },
  {
    id: 'translate-pdf',
    title: 'Layout-Preserving Translator',
    description: 'Translate PDF text into 50+ languages while preserving exact fonts and table structures.',
    category: 'ai-intelligence',
    iconName: 'Languages',
    badge: 'AI',
    accentColor: 'purple',
    keywords: ['translate', 'multilingual', 'spanish', 'french', 'hindi', 'language'],
  },
  {
    id: 'contract-risk-analyzer',
    title: 'Contract & Legal Risk Analyzer',
    description: 'Identify high-risk indemnity clauses, auto-renewals, non-competes, and liability traps.',
    category: 'ai-intelligence',
    iconName: 'Scale',
    badge: 'PRO',
    accentColor: 'rose',
    keywords: ['contract', 'legal', 'risk', 'nda', 'analyzer', 'clauses'],
  },
  {
    id: 'resume-ats-reviewer',
    title: 'Resume Reviewer & ATS Scorer',
    description: 'Score CVs against job descriptions and get actionable ATS keyword enhancements.',
    category: 'ai-intelligence',
    iconName: 'UserCheck',
    badge: 'AI',
    accentColor: 'emerald',
    keywords: ['resume', 'cv', 'ats', 'job', 'score', 'career'],
  },
  {
    id: 'ocr-searchable-pdf',
    title: 'Searchable PDF (Tesseract WASM)',
    description: 'On-device OCR in 100+ languages to inject an invisible searchable text layer into scans.',
    category: 'ai-intelligence',
    iconName: 'ScanText',
    badge: 'WASM',
    accentColor: 'cyan',
    keywords: ['ocr', 'tesseract', 'searchable', 'scan', 'optical character recognition'],
    isFeatured: true,
  },
  {
    id: 'compare-pdfs',
    title: 'Dual Sync Diff & Heatmap Compare',
    description: 'Side-by-side synchronized viewer with pixel-diff heatmap overlay and text diffing.',
    category: 'ai-intelligence',
    iconName: 'GitCompare',
    badge: 'PRO',
    accentColor: 'blue',
    keywords: ['compare', 'diff', 'side by side', 'heatmap', 'revisions'],
  },
  {
    id: 'quiz-flashcard-generator',
    title: 'AI Flashcard & Quiz Generator',
    description: 'Auto-generate study flashcards and multiple-choice quizzes from manuals or textbooks.',
    category: 'ai-intelligence',
    iconName: 'GraduationCap',
    badge: 'AI',
    accentColor: 'purple',
    keywords: ['quiz', 'flashcards', 'study', 'test', 'education'],
  },

  // ─────────────────────────────────────────────────────────────
  // 7. CYBER SUPER-MODULES
  // ─────────────────────────────────────────────────────────────
  {
    id: 'node-workflow-builder',
    title: 'Visual Node Automation Graph',
    description: 'Drag & connect modular nodes (ComfyUI / Blueprint style) to run custom batch pipelines.',
    category: 'super-modules',
    iconName: 'Workflow',
    badge: 'PRO',
    accentColor: 'cyan',
    keywords: ['nodes', 'workflow', 'automation', 'pipeline', 'graph', 'blueprint'],
    isFeatured: true,
  },
  {
    id: '3d-flipbook-presenter',
    title: '3D Holographic Flipbook',
    description: 'Transform any PDF into a 3D physical book with page physics, laser pointer, and HUD notes.',
    category: 'super-modules',
    iconName: 'Box',
    badge: 'HOT',
    accentColor: 'purple',
    keywords: ['3d', 'flipbook', 'presentation', 'laser', 'book'],
    isFeatured: true,
  },
  {
    id: 'p2p-file-share',
    title: 'P2P WebRTC Direct Share',
    description: 'Direct browser-to-browser encrypted file transfer with instant QR code room pairing.',
    category: 'super-modules',
    iconName: 'Share2',
    badge: 'WASM',
    accentColor: 'emerald',
    keywords: ['p2p', 'webrtc', 'share', 'direct', 'qr code', 'transfer'],
  },
  {
    id: 'collab-whiteboard',
    title: 'Multiplayer Review Whiteboard',
    description: 'Real-time collaborative document review canvas over peer-to-peer WebRTC.',
    category: 'super-modules',
    iconName: 'Users',
    badge: 'NEW',
    accentColor: 'blue',
    keywords: ['whiteboard', 'collab', 'multiplayer', 'webrtc', 'real-time'],
  },

  // ─────────────────────────────────────────────────────────────
  // 8. COMMERCE & INVOICING
  // ─────────────────────────────────────────────────────────────
  {
    id: 'gst-invoice-generator',
    title: 'GST Tax Invoice Generator',
    description: 'Indian Tax invoice builder with auto CGST/SGST/IGST computation, HSN, and QR codes.',
    category: 'business',
    iconName: 'ReceiptText',
    badge: 'HOT',
    accentColor: 'amber',
    keywords: ['gst', 'invoice', 'tax', 'cgst', 'sgst', 'igst', 'hsn'],
    isFeatured: true,
  },
  {
    id: 'pos-thermal-billing',
    title: 'POS Thermal Billing Engine',
    description: 'Point-of-sale register with 58mm/80mm thermal receipt printing and barcode scanning.',
    category: 'business',
    iconName: 'Printer',
    accentColor: 'amber',
    keywords: ['pos', 'thermal', 'receipt', 'barcode', 'register', 'shop'],
  },
  {
    id: 'eway-bill-generator',
    title: 'E-Way & Delivery Challan',
    description: 'Generate formatted transport, dispatch, and delivery challan PDFs for logistics.',
    category: 'business',
    iconName: 'Truck',
    accentColor: 'amber',
    keywords: ['eway', 'challan', 'delivery', 'logistics', 'transport'],
  },
  {
    id: 'gst-filing-prep',
    title: 'GST Filing & ITC Reconciler',
    description: 'Consolidate multiple invoice PDFs and calculate monthly Input Tax Credit summaries.',
    category: 'business',
    iconName: 'Calculator',
    accentColor: 'amber',
    keywords: ['gst filing', 'itc', 'tax summary', 'reconcile'],
  },
];

export const getAllTools = (): ToolDefinition[] => TOOLS_REGISTRY;

export const getToolById = (id: string): ToolDefinition | undefined =>
  TOOLS_REGISTRY.find((tool) => tool.id === id);

export const getToolsByCategory = (category: ToolCategory): ToolDefinition[] =>
  TOOLS_REGISTRY.filter((tool) => tool.category === category);

export const getFeaturedTools = (): ToolDefinition[] =>
  TOOLS_REGISTRY.filter((tool) => tool.isFeatured);

export const searchTools = (query: string): ToolDefinition[] => {
  const cleanQuery = query.toLowerCase().trim();
  if (!cleanQuery) return TOOLS_REGISTRY;

  return TOOLS_REGISTRY.filter((tool) => {
    const titleMatch = tool.title.toLowerCase().includes(cleanQuery);
    const descMatch = tool.description.toLowerCase().includes(cleanQuery);
    const keywordMatch = tool.keywords.some((kw) => kw.toLowerCase().includes(cleanQuery));
    const categoryMatch = tool.category.toLowerCase().includes(cleanQuery);

    return titleMatch || descMatch || keywordMatch || categoryMatch;
  });
};